return {
	disable_booster_tag = false,
	only_ygo_cards = true,
	extra_ygo_booster = true,
	disable_tooltips = false,
	instant_poker_hand = false,
	disable_main_menu = false,
	disable_glow = false,
	disable_counters = false,
	alt_art = {
		j_joy_dmaid_house = 1,
		j_joy_etwin_kisikil = 1,
		j_joy_etwin_lilla = 1,
		j_joy_dogma_ecclesia = 1,
		j_joy_yokai_ash = 1,
		j_joy_yokai_belle = 1,
		j_joy_lab_lady = 1,
		j_joy_eld_eldlich = 1,
		j_joy_shaddoll_winda = 1,
		j_joy_shaddoll_elconstruct = 1,
		j_joy_invoked_aleister = 1,
		j_joy_invoked_mechaba = 1,
		j_joy_apollousa = 1,
		j_joy_ipmasq = 1,
		j_joy_striker_raye = 1,
		j_joy_striker_hayate = 1,
		j_joy_striker_kagari = 1,
		j_joy_striker_shizuku = 1,
		j_joy_dm_dm = 1,
		j_joy_dm_dmg = 1,
		j_joy_spknight = 1,
		j_joy_parasiteparacide = 1,
	}
}
