--- MISCELLANEOUS

--- 0.7.0

--- 0.8.0
-- SMODS.Joker({
--     key = "zenoguitar",
--     atlas = 'Misc02',
--     pos = { x = 1, y = 1 },
--     rarity = 1,
--     discovered = true,
--     blueprint_compat = false,
--     eternal_compat = true,
--     cost = 0,
--     loc_vars = function(self, info_queue, card)
--         return { vars = {} }
--     end,
--     generate_ui = JoyousSpring.generate_info_ui,
--     set_sprites = JoyousSpring.set_back_sprite,
--     config = {
--         extra = {
--             joyous_spring = JoyousSpring.init_joy_table {
--                 attribute = "EARTH",
--                 monster_type = "Rock",
--             },
--         },
--     },
-- })
-- SMODS.Joker({
--     key = "revgolem",
--     atlas = 'Misc02',
--     pos = { x = 0, y = 1 },
--     rarity = 1,
--     discovered = true,
--     blueprint_compat = false,
--     eternal_compat = true,
--     cost = 0,
--     loc_vars = function(self, info_queue, card)
--         return { vars = {} }
--     end,
--     generate_ui = JoyousSpring.generate_info_ui,
--     set_sprites = JoyousSpring.set_back_sprite,
--     config = {
--         extra = {
--             joyous_spring = JoyousSpring.init_joy_table {
--                 attribute = "EARTH",
--                 monster_type = "Rock",
--             },
--         },
--     },
-- })
-- SMODS.Joker({
--     key = "tackcrusader",
--     atlas = 'Misc02',
--     pos = { x = 2, y = 1 },
--     rarity = 1,
--     discovered = true,
--     blueprint_compat = false,
--     eternal_compat = true,
--     cost = 0,
--     loc_vars = function(self, info_queue, card)
--         return { vars = {} }
--     end,
--     generate_ui = JoyousSpring.generate_info_ui,
--     set_sprites = JoyousSpring.set_back_sprite,
--     config = {
--         extra = {
--             joyous_spring = JoyousSpring.init_joy_table {
--                 attribute = "EARTH",
--                 monster_type = "Rock",
--             },
--         },
--     },
-- })
-- SMODS.Joker({
--     key = "doki",
--     atlas = 'Misc02',
--     pos = { x = 2, y = 0 },
--     rarity = 1,
--     discovered = true,
--     blueprint_compat = false,
--     eternal_compat = true,
--     cost = 0,
--     loc_vars = function(self, info_queue, card)
--         return { vars = {} }
--     end,
--     generate_ui = JoyousSpring.generate_info_ui,
--     set_sprites = JoyousSpring.set_back_sprite,
--     config = {
--         extra = {
--             joyous_spring = JoyousSpring.init_joy_table {
--                 attribute = "EARTH",
--                 monster_type = "Rock",
--             },
--         },
--     },
-- })
-- SMODS.Joker({
--     key = "blockdragon",
--     atlas = 'Misc02',
--     pos = { x = 1, y = 0 },
--     rarity = 1,
--     discovered = true,
--     blueprint_compat = false,
--     eternal_compat = true,
--     cost = 0,
--     loc_vars = function(self, info_queue, card)
--         return { vars = {} }
--     end,
--     generate_ui = JoyousSpring.generate_info_ui,
--     set_sprites = JoyousSpring.set_back_sprite,
--     config = {
--         extra = {
--             joyous_spring = JoyousSpring.init_joy_table {
--                 attribute = "EARTH",
--                 monster_type = "Rock",
--             },
--         },
--     },
-- })
