[manifest]
version = "0.1.0"
dump_lua = true
priority = 0

# Add Hanafuda enhancements to poker hand screen
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''local card = Card(0,0, 0.5*G.CARD_W, 0.5*G.CARD_H, G.P_CARDS[v[1]], G.P_CENTERS[v.enhancement or 'c_base'])'''
position = "after"
payload = '''
if v.joy_hanafuda then
    G.E_MANAGER:add_event(Event({
        blockable = false,
        func = (function()
            card.children.center:set_sprite_pos(JoyousSpring.hanafuda_cards[v.joy_hanafuda].pos)
            return true
        end)
    }))
end
'''
match_indent = true

# Add Hanafuda sorting
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''
{n=G.UIT.T, config={text = localize('k_suit'), scale = text_scale*0.7, colour = G.C.UI.TEXT_LIGHT}}
}}
'''
position = "after"
payload = '''
,JoyousSpring.create_hanafuda_month_sort_UIBox(),
JoyousSpring.create_hanafuda_type_sort_UIBox()
'''
match_indent = true

# Add controller UI
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''
--The card UI can have BUY, REDEEM, USE, and SELL buttons depending on the context of the card
'''
position = "after"
payload = '''
if JoyousSpring.is_monster_card(card) then
    return JoyousSpring.card_focus_ui(card, base_background)
end
'''
match_indent = true

# Stuff for Info Menu
[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
match_indent = true
position = 'at'
pattern = '''
if args.type == 'other' then
'''
payload = '''
if args.loc_target then
    loc_target = args.loc_target
elseif args.type == 'other' then
'''

# Replace splash screen cards (copied from Maximus <3)
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
SC = Card(G.ROOM.T.w/2 - SC_scale*G.CARD_W/2, 10. + G.ROOM.T.h/2 - SC_scale*G.CARD_H/2, SC_scale*G.CARD_W, SC_scale*G.CARD_H, G.P_CARDS.empty, G.P_CENTERS['j_joker'])
'''
position = "after"
payload = '''
if JoyousSpring and not JoyousSpring.config.disable_main_menu then
    math.randomseed(os.time())
    local joy_center, _ = G.P_CENTER_POOLS.joy_monster[math.random(1, #G.P_CENTER_POOLS.joy_monster)]
    SC = Card(G.ROOM.T.w/2 - SC_scale*G.CARD_W/2, 10. + G.ROOM.T.h/2 - SC_scale*G.CARD_H/2, SC_scale*G.CARD_W, SC_scale*G.CARD_H, G.P_CARDS.empty, joy_center,{bypass_discovery_center = true, bypass_discovery_ui = true})
end
'''
match_indent = true


[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
local card = Card(  card_pos.x + G.ROOM.T.w/2 - G.CARD_W*card_size/2,
                    card_pos.y + G.ROOM.T.h/2 - G.CARD_H*card_size/2,
                    card_size*G.CARD_W, card_size*G.CARD_H, pseudorandom_element(G.P_CARDS), G.P_CENTERS.c_base)
'''
position = "at"
payload = '''
local card
if JoyousSpring and not JoyousSpring.config.disable_main_menu then
    local joy_center, _ = G.P_CENTER_POOLS.joy_monster[math.random(1, #G.P_CENTER_POOLS.joy_monster)]
    card = Card(  card_pos.x + G.ROOM.T.w/2 - G.CARD_W*card_size/2,
                        card_pos.y + G.ROOM.T.h/2 - G.CARD_H*card_size/2,
                        card_size*G.CARD_W, card_size*G.CARD_H, G.P_CARDS.empty, joy_center,{bypass_discovery_center = true, bypass_discovery_ui = true})
else
    card = Card(  card_pos.x + G.ROOM.T.w/2 - G.CARD_W*card_size/2,
                    card_pos.y + G.ROOM.T.h/2 - G.CARD_H*card_size/2,
                    card_size*G.CARD_W, card_size*G.CARD_H, pseudorandom_element(G.P_CARDS), G.P_CENTERS.c_base)
end
'''
match_indent = true
times = 1

# Replace splash screen colours
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
{name = 'colour_1', ref_table = G.C, ref_value = 'BLUE'},
{name = 'colour_2', ref_table = G.C, ref_value = 'WHITE'},
'''
position = "at"
payload = '''
JoyousSpring and not JoyousSpring.config.disable_main_menu and { name = "colour_1",   ref_table = G.C.JOY,  ref_value = "EFFECT" } or {name = 'colour_1', ref_table = G.C, ref_value = 'BLUE'},
JoyousSpring and not JoyousSpring.config.disable_main_menu and { name = "colour_2",   ref_table = G.C,      ref_value = "BLACK" } or {name = 'colour_2', ref_table = G.C, ref_value = 'WHITE'},
'''
match_indent = true
times = 1

# Replace screenwipe card
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''
G.screenwipecard = Card(1, 1, G.CARD_W, G.CARD_H, pseudorandom_element(G.P_CARDS), G.P_CENTERS.c_base)
'''
position = "at"
payload = '''
if JoyousSpring and not JoyousSpring.config.disable_main_menu then
    G.screenwipecard = Card(1, 1, G.CARD_W, G.CARD_H, G.P_CARDS.empty, pseudorandom_element(G.P_CENTER_POOLS.joy_monster))
else
    G.screenwipecard = Card(1, 1, G.CARD_W, G.CARD_H, pseudorandom_element(G.P_CARDS), G.P_CENTERS.c_base)
end
'''
match_indent = true
times = 1

# Replace main menu colours
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
{name = 'colour_1', ref_table = G.C, ref_value = 'RED'},
{name = 'colour_2', ref_table = G.C, ref_value = 'BLUE'},
'''
position = "at"
payload = '''
JoyousSpring and not JoyousSpring.config.disable_main_menu and { name = "colour_1",   ref_table = G.C.JOY,  ref_value = "EFFECT" } or {name = 'colour_1', ref_table = G.C, ref_value = 'RED'},
JoyousSpring and not JoyousSpring.config.disable_main_menu and { name = "colour_2",   ref_table = G.C,      ref_value = "BLACK" } or {name = 'colour_2', ref_table = G.C, ref_value = 'BLUE'},
'''
match_indent = true
times = 1
