[manifest]
version = "0.1.0"
dump_lua = true
priority = 0

# Opponent Jokers

# Change shadow
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/card_draw.lua"]'
pattern = "G.shared_shadow:draw_shader('dissolve', self.shadow_height)"
position = 'before'
match_indent = true
payload = '''
if JoyousSpring then
    if self.area and (self.area == JoyousSpring.opponent_area or self.area == G.joy_blind_effects_area) then
        self.shadow_height = 0.04
    end
end
'''

# Add to collection
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''
UIBox_button({button = 'your_collection_jokers', label = {localize('b_jokers')}, count = G.DISCOVER_TALLIES.jokers,  minw = 5, minh = 1.7, scale = 0.6, id = 'your_collection_jokers'}),
'''
position = 'after'
match_indent = true
payload = '''
JoyousSpring and JoyousSpring.config.only_ygo_cards and UIBox_button({button = 'joy_your_collection_opponent', label = {localize('k_joy_opponentcards')}, count = JoyousSpring.opponent_collection_tally(), minw = 5, id = 'joy_your_collection_opponent'}) or nil,
'''

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/ui.lua"]'
pattern = "local rightside_nodes = {}"
position = 'before'
match_indent = true
payload = '''
if JoyousSpring then
    local tally = modsCollectionTally(G.P_CENTER_POOLS.joy_Opponent)
    if tally.of > 0 then
        local joy_button = UIBox_button({button = 'joy_your_collection_opponent', label = {localize('k_joy_opponentcards')}, count = modsCollectionTally(G.P_CENTER_POOLS.joy_Opponent), minw = 5, id = 'joy_your_collection_opponent'})
        table.insert(leftside_nodes, 2, joy_button)
    end
end
'''
